/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminMarketplaceRouteImport } from './routes/admin.marketplace'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEspacosRouteImport } from './routes/admin.espacos'
import { Route as AdminCheckinRouteImport } from './routes/admin.checkin'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminReservasIndexRouteImport } from './routes/admin.reservas.index'
import { Route as ApiPublicHooksLembretesRouteImport } from './routes/api/public/hooks/lembretes'
import { Route as AdminReservasIdEditarRouteImport } from './routes/admin.reservas.$id.editar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEspacosRoute = AdminEspacosRouteImport.update({
  id: '/espacos',
  path: '/espacos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasIndexRoute = AdminReservasIndexRouteImport.update({
  id: '/reservas/',
  path: '/reservas/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksLembretesRoute = ApiPublicHooksLembretesRouteImport.update({
  id: '/api/public/hooks/lembretes',
  path: '/api/public/hooks/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasIdEditarRoute = AdminReservasIdEditarRouteImport.update({
  id: '/reservas/$id/editar',
  path: '/reservas/$id/editar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/convite': typeof ConviteRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/espacos': typeof AdminEspacosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reservas/': typeof AdminReservasIndexRoute
  '/admin/reservas/$id/editar': typeof AdminReservasIdEditarRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convite': typeof ConviteRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/espacos': typeof AdminEspacosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/reservas': typeof AdminReservasIndexRoute
  '/admin/reservas/$id/editar': typeof AdminReservasIdEditarRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/convite': typeof ConviteRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/espacos': typeof AdminEspacosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reservas/': typeof AdminReservasIndexRoute
  '/admin/reservas/$id/editar': typeof AdminReservasIdEditarRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/convite'
    | '/dashboard'
    | '/sitemap.xml'
    | '/admin/agenda'
    | '/admin/checkin'
    | '/admin/espacos'
    | '/admin/financeiro'
    | '/admin/marketplace'
    | '/admin/pagamentos'
    | '/admin/relatorios'
    | '/admin/'
    | '/admin/reservas/'
    | '/admin/reservas/$id/editar'
    | '/api/public/hooks/lembretes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convite'
    | '/dashboard'
    | '/sitemap.xml'
    | '/admin/agenda'
    | '/admin/checkin'
    | '/admin/espacos'
    | '/admin/financeiro'
    | '/admin/marketplace'
    | '/admin/pagamentos'
    | '/admin/relatorios'
    | '/admin'
    | '/admin/reservas'
    | '/admin/reservas/$id/editar'
    | '/api/public/hooks/lembretes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/convite'
    | '/dashboard'
    | '/sitemap.xml'
    | '/admin/agenda'
    | '/admin/checkin'
    | '/admin/espacos'
    | '/admin/financeiro'
    | '/admin/marketplace'
    | '/admin/pagamentos'
    | '/admin/relatorios'
    | '/admin/'
    | '/admin/reservas/'
    | '/admin/reservas/$id/editar'
    | '/api/public/hooks/lembretes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConviteRoute: typeof ConviteRoute
  DashboardRoute: typeof DashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksLembretesRoute: typeof ApiPublicHooksLembretesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/espacos': {
      id: '/admin/espacos'
      path: '/espacos'
      fullPath: '/admin/espacos'
      preLoaderRoute: typeof AdminEspacosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas/': {
      id: '/admin/reservas/'
      path: '/reservas'
      fullPath: '/admin/reservas/'
      preLoaderRoute: typeof AdminReservasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/lembretes': {
      id: '/api/public/hooks/lembretes'
      path: '/api/public/hooks/lembretes'
      fullPath: '/api/public/hooks/lembretes'
      preLoaderRoute: typeof ApiPublicHooksLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservas/$id/editar': {
      id: '/admin/reservas/$id/editar'
      path: '/reservas/$id/editar'
      fullPath: '/admin/reservas/$id/editar'
      preLoaderRoute: typeof AdminReservasIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminCheckinRoute: typeof AdminCheckinRoute
  AdminEspacosRoute: typeof AdminEspacosRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReservasIndexRoute: typeof AdminReservasIndexRoute
  AdminReservasIdEditarRoute: typeof AdminReservasIdEditarRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminCheckinRoute: AdminCheckinRoute,
  AdminEspacosRoute: AdminEspacosRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReservasIndexRoute: AdminReservasIndexRoute,
  AdminReservasIdEditarRoute: AdminReservasIdEditarRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConviteRoute: ConviteRoute,
  DashboardRoute: DashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksLembretesRoute: ApiPublicHooksLembretesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
