/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminMarketplaceRouteImport } from './routes/admin.marketplace'
import { Route as AdminEspacosRouteImport } from './routes/admin.espacos'
import { Route as AdminCheckinRouteImport } from './routes/admin.checkin'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as ApiPublicHooksLembretesRouteImport } from './routes/api/public/hooks/lembretes'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEspacosRoute = AdminEspacosRouteImport.update({
  id: '/espacos',
  path: '/espacos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksLembretesRoute = ApiPublicHooksLembretesRouteImport.update({
  id: '/api/public/hooks/lembretes',
  path: '/api/public/hooks/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/convite': typeof ConviteRoute
  '/dashboard': typeof DashboardRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/espacos': typeof AdminEspacosRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convite': typeof ConviteRoute
  '/dashboard': typeof DashboardRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/espacos': typeof AdminEspacosRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/convite': typeof ConviteRoute
  '/dashboard': typeof DashboardRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/espacos': typeof AdminEspacosRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/convite'
    | '/dashboard'
    | '/admin/agenda'
    | '/admin/checkin'
    | '/admin/espacos'
    | '/admin/marketplace'
    | '/admin/reservas'
    | '/admin/'
    | '/api/public/hooks/lembretes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convite'
    | '/dashboard'
    | '/admin/agenda'
    | '/admin/checkin'
    | '/admin/espacos'
    | '/admin/marketplace'
    | '/admin/reservas'
    | '/admin'
    | '/api/public/hooks/lembretes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/convite'
    | '/dashboard'
    | '/admin/agenda'
    | '/admin/checkin'
    | '/admin/espacos'
    | '/admin/marketplace'
    | '/admin/reservas'
    | '/admin/'
    | '/api/public/hooks/lembretes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConviteRoute: typeof ConviteRoute
  DashboardRoute: typeof DashboardRoute
  ApiPublicHooksLembretesRoute: typeof ApiPublicHooksLembretesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/espacos': {
      id: '/admin/espacos'
      path: '/espacos'
      fullPath: '/admin/espacos'
      preLoaderRoute: typeof AdminEspacosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/lembretes': {
      id: '/api/public/hooks/lembretes'
      path: '/api/public/hooks/lembretes'
      fullPath: '/api/public/hooks/lembretes'
      preLoaderRoute: typeof ApiPublicHooksLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminCheckinRoute: typeof AdminCheckinRoute
  AdminEspacosRoute: typeof AdminEspacosRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminCheckinRoute: AdminCheckinRoute,
  AdminEspacosRoute: AdminEspacosRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConviteRoute: ConviteRoute,
  DashboardRoute: DashboardRoute,
  ApiPublicHooksLembretesRoute: ApiPublicHooksLembretesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
